config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"

  get "events/filter/:show_only", to: "events#index", as: :filtered_events

  resources :categories
  
  # Since registrations only make sense in the context of events
  # we should nest the registrations routes under the event routes
  # This sets up a hierarchy: the event id must be present in the routes
  # for registrations path
  # like events/:id/registrations/new
  # the registration related routes are embeded under events/:id
  resources :events do
    resources :registrations
    resources :likes
  end

  # since there will be only one session per user, we use the singular form of resource and the resource name (:session)
  # this way the routes won't contain an :id param for destroying a session
  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "signup", to: "users#new"
    
  
  # get "events", to: "events#index"
  # get "events/new", to: "events#new"
  # get "events/:id", to: "events#show", as: "event"
  # get "events/:id/edit", to: "events#edit", as: "edit_event"
  # patch "events/:id", to: "events#update"
end

app/models/user.rb
class User < ApplicationRecord

  has_many :registrations, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :liked_events, through: :likes, source: :event

  # when generating the user resource with password:digest, it will give us the has_secure_password, that generate some convenience methods and validations for storing password in a safe way
  # but we need an additional Ruby gem for this to work, bcrypt
  # has_secure_password will add a password virtual attribute to the user. If we write to the user's password attribute (user.password = "secret"), it will hash the password and store it under user.password_digest
  # it will also add a password_confirmation attribute and validation if the password and password_confirmations match

  # the password and password_confirmation are virtual attributes. They do not have a corresponding column in the database
  # when we assign to the password, like u.password = "secret"
  # the has_secure_password runs a method, the password= method
  # this method hashes the plain text password and saves the plain password to an instance variable
  # def password=("secret")
    # self.password_digest = "hashed value"
    # @password = "secret"
  # end
  # when we set the password_confirmation attribute has_secure_password runs the password_confirmation= method. It simply assigns the plain password_confirmation value to an instance variable
  # def password_confirmation=("secret")
    # @password_confirmation = "secret"
  # end
  # the the built-in validation check if the @password and @password_confirmation intance variable match
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/, message: "must be a valid email address"},
            # before saving a user to the db, uniqueness checks if the email already exists in the db. By default it is case sensitive
            uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # set up a gatekeeper method
  # it will redirect to the user to the signin page before every action, except new and create
  # require_signin is defined in the ApplicationController, so it is available from any controllers
  before_action :require_signin, except: [:new, :create]

  # the second gatekeeper method makes sure that the action only run if the currently signed in user is the correct user
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  # The order of before_action methods matter. They are executed from top to bottom. 
  # If any of them redirects, the before_actions below it won't run


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # if a new user account is created we immediately sign her in by putting her id in the session
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    # we can remove this line from the edit, update and destroy actions, since it is defined in the require_correct_user method
    # @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    # when a user deletes his account, we also need to clear his id from the session
    session[:user_id] = nil
    redirect_to events_url, alert: "Account successfully deleted"
  end



  private

    def user_params
      params.require(:user)
        .permit(:name, :email, :password, :password_confirmation)
    end

    # since require_correct_user will only be used in the UsersController, we can define it here
    def require_correct_user
      # first we fetch the user whose profile page we want to access
      @user = User.find(params[:id])
      # then we check if this user is the same as the currently signed in user
      # current_user? is defined in the ApplicationController
      redirect_to events_url, alert: "Unauthorized action!" unless current_user?(@user)
    
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render("shared/errors", object: user) %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Retype Your Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render("form", user: @user) %>

app/views/users/index.html.erb
<h1>
  <%= pluralize(@users.size, "Users") %>
</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
      signed up
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render("form", user: @user) %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>

  <%# the current_user? method checks if the currently signed in user is the same whose profile page we visit %>
  <%# it take a parameter, the user whose page we visit %>
  <%# this method is defined in the ApplicationController since we may want to use it from other controllers %>
  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
      <%= link_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "button delete" %>
    </div>
  <% end %>

  <% if @registrations.present? %>
    <h3>Registrations</h3>
    <% @registrations.each do |r| %>
      <div class="registration">
        <div class="image">
          <%= link_to main_image(r.event), r.event %>
        </div>
        <div class="name">
          <%= link_to r.event.name, r.event %>
        </div>
        <div class="date">
          <%= time_ago_in_words(r.created_at) %> ago
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @liked_events.present? %>
    <h3>Liked Events</h3>
    <div class="liked-events">
      <% @liked_events.each do |event| %>
        <%= link_to main_image(event), event_path(event) %>
      <% end %>
    </div>
  <% end %>
</section>