config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"

  get "events/filter/:show_only", to: "events#index", as: :filtered_events

  resources :categories
  
  # Since registrations only make sense in the context of events
  # we should nest the registrations routes under the event routes
  # This sets up a hierarchy: the event id must be present in the routes
  # for registrations path
  # like events/:id/registrations/new
  # the registration related routes are embeded under events/:id
  resources :events do
    resources :registrations
    resources :likes
  end

  # since there will be only one session per user, we use the singular form of resource and the resource name (:session)
  # this way the routes won't contain an :id param for destroying a session
  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "signup", to: "users#new"
    
  
  # get "events", to: "events#index"
  # get "events/new", to: "events#new"
  # get "events/:id", to: "events#show", as: "event"
  # get "events/:id/edit", to: "events#edit", as: "edit_event"
  # patch "events/:id", to: "events#update"
end

app/models/event.rb
class Event < ApplicationRecord

  # ActiveRecord callbacks
  # these are methods that run at certain point in the model object's life cycle
  # available callbacks:
  # before_validation
  # after_validation
  # before_save
  # after_save
  before_save :set_slug

  # the has_many declartion gives us methods on an event object to access its associated registrations
  # to get the registrations for the event
  # event.registrations
  # to create registration for an event
  # event.registration.new()
  has_many :registrations, dependent: :destroy
          # :dependent :destroy makes sure all children registration are destroyed when an event is destroyed
  
  has_many :likes, dependent: :destroy

  # we declare that an event has many likers though the likes association
  # the source option defines what a liker is. it is a user
  has_many :likers, through: :likes, source: :user

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  # Using ActiveStorage
  # this declaration says there is one main image for an event
  # main_image is a custom name, we can choose it
  has_one_attached :main_image

  # the has_one_attached method basically creates two associations:
  # has_one :main_image_attachment, dependent: :destroy
  # has_one :main_image_blob, through: :main_image_attachment
           

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, length: {minimum: 20, maximum: 400}
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :capacity, numericality: 
                      {greater_than: 0, only_integer: true}

  # Defining our own custom validation with validate and a method name
  validate :acceptable_image
  

  # A scope defines a class method for us dinamically
  # first parameter is the name of the method/scope, the second is the query
  # We can think of a scope as simply a named custom query
  # the query needs to be reevaluated every time the scope is called
  # therefore the second parameter must be a callable object
  # for this, we need to use lambda with curly braces
  # the lamba turn the block into a callable object, also called a Proc object
  # instead of the word 'lambda' we can use an arrow ->
  scope :past, lambda { where("starts_at < ?", Time.now).order("starts_at") }

  scope :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at") }

  # scope for upcoming free events
  scope :free, -> { upcoming.where(price: 0).order("starts_at") }
  # We can also chain scope together, like Event.upcoming.free

  # scope for the past n number of events
  # we pass arguments to a scope, event provide a default value
  scope :recent, ->(n=3) { past.limit(n) }

  # put class method on top
  # class methods work on the whole class and defined by 'self'
  # def self.upcoming
  #   # you do not need to put 'self' in front, because we already used in the method name
  #   # the class is the implicit reciever of the statement below
  #   where("starts_at > ?", Time.now).order("starts_at")
  # end

  # these methods basically just give a name to a query (upcoming, past)
  # this works, but Rails gives us another ways to define custom queries
  # it's called a scope
  # def self.past
  #   where("starts_at < ?", Time.now).order("starts_at")
  # end

  def free?
    price.blank? || price.zero?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end

  # overriding the default to_param method
  # instead of returning the string representaion of event id, now it returns its name
  def to_param
    # we need to turn the name into a url friendly format by the parameterize method
    # this return a name like "kata-camp"
    # name.parameterize

    # we just return what to set_slug callback returns, the slug
    slug
  end

  private

    # defining a before_save callback
    def set_slug
      # we need to use self when we assign the a model's attribute
      # otherwise slug will just be treated as a local variable, not an attribute
      # we don't need self before reading an attribute (like "name" in this case), only when we are assigning a value to an attribute
      self.slug = name.parameterize
    end

    def acceptable_image
      # first we check if the event has an attached image at all
      # it it does not, we do not run the method
      return unless main_image.attached?

      unless main_image.byte_size <= 1.megabyte
        # if the attached image is larger than 1MB we add to the error collection a custom message for the main_image attribute
        errors.add(:main_image, "is too big")
      end

      acceptable_formats = ["image/jpeg", "image/png"]
      unless acceptable_formats.include?(main_image.content_type)
        errors.add(:main_image, "must be a JPEG or PNG")
      end

    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    case params[:show_only]
    when "upcoming" 
      @events = Event.upcoming
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent
    when "past"
      @events = Event.past
    else
      @events = Event.all
    end
  end

  def show
    # fail
    # params[:id] contains the slug, not the actual id of the event
    # so we need to change how we find an event
    # @event = Event.find(params[:id])
    # @event = Event.find_by!(slug: params[:id])
    @likers = @event.likers

    # we need to determine whether the current user already liked this event or not
    # we can check if there is a row in the likes table that has this event's id and the current user's id

    # current_user.likes returns only those row where the user_id coloum equals the current_user's 
    # then we can further run the find_by method on the subset of records to further scope down to those records where the event_id coloum equals the this event's is
    # Rails will generate only one SQL query to do this
    # this query returns a like object or nil
    # we only want to query for the like object if the user is signed in
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end

    @categories = @event.categories
  end

  def edit
    # @event = Event.find(params[:id])
  end

  def update
    # @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "Event successfully updated"
      redirect_to @event
    else
      render :edit
    end
    
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def destroy
    # @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

  private

  def event_params
    params
      .require(:event)
      # the category_ids attribute will be passed as an array, so we need to specify it as an array
      .permit(:name, :description, :location, :price, :starts_at, :capacity, :main_image, category_ids: [])
  end

  def set_event
    @event = Event.find_by!(slug: params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def price(event)
    event.free? ? "Free" : number_to_currency(event.price, precision: 2)
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d, %Y at %I:%M %P")
  end

  def main_image(event)
    # ActiveStorage gives us an attached? method to check if an event has a main image attached to it
    if event.main_image.attached?
      image_tag event.main_image.variant(resize_to_limit: [75, 75])
    else
      image_tag "placeholder.png"
    end
  end

end

app/views/events/_form.html.erb
<!-- the form_with helper by default is using AJAX to submit the form -->
<!-- We can disable it by setting to local option to true -->
<%= form_with(model: event, local: true) do |f| %>

  <%= render "shared/errors", object: event %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity %>

  <%= f.label :main_image %>
  <%= f.file_field :main_image %>

  <%= f.label "Categories" %>
  <div class="checkboxes">
    <%# the collection_check_boxes takes 4 parameters %>
    <%# the first is the name of attribute of the event (this will be included in the params hash) %>
    <%# the second is the collection of object we want checkboxes for %>
    <%# the third is the value to use for the checkbox input (the id) %>
    <%# the fourth is the text to be displayed next to the checkbox %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </div>

  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <section class="event">
    <div class="image">
      <%= main_image(event) %>
    </div>
    <div class="summary">
      <%# the event_path(event) method generates a route for the event %>
      <%# how does it do it? %>
      <%# in the Rails console, we can run app.event_path(event) %>
      <%# it returns "/events/3" %>
      <%# it's reasonable to think that Rails is reading the id attribute of the event %>
      <%# but that is not what's happening %>
      <%# Rails runs a method to_param on all ActiveRecord objects %>
      <%# like event.to_param %>
      <%# the method converts the object to a string of its id, "3" %>
      <%# we can override the default behavior of the to_param method in the model class %>
      <h2><%= link_to event.name, event_path(event) %></h2>
      <h3><%= day_and_time(event) %> in <%= event.location %></h3>
      <span class="price">
        <%= price(event) %>
      </span>     
      <p>
        <%= truncate(event.description, length: 35, separator: " ") %>
      </p>  
    </div>
  </section>
<% end %>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Event", new_event_path, class: "button" %>
  </section>
<% end %>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

 <%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <div class="image">
    <%= main_image(@event) %>
    <% if current_user %>
      <div class="likes">
        <%= like_or_unlike_button(@event, @like) %>
        <div class="count">
          <%= @likers.size %>
      </div>
      </div>
    <% end %>
  </div>
  <div class="details">
    <h1>
      <%= @event.name %>
    </h1>
    <h2>
      <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %>
    </h2>
    <h3>
      <%= day_and_time(@event) %> in <%= @event.location %>
    </h3>
    <p>
      <%= @event.description %>
    </p>
    <div class="register">
      <%= register_or_sold_out(@event) %>
      <p>
       <%= link_to "Who's registred?", event_registrations_path(@event) %>
      </p>
    </div>
  </div>

  <aside>
    <% if @likers.present? %>
      <h4>Liked By</h4>
      <ul>
        <% @likers.each do |user| %>
          <li>
            <%= link_to user.name, user_path(user) %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if @categories.present? %>
      <h4>Categories</h4>
      <ul>
        <% @categories.each do |c| %>
          <li><%= c.name %></li>
        <% end %>
      </ul>
    <% end %>
  </aside>
</section>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_event_path(@event), class: "button" %>
    <%= link_to "Delete", event_path(@event), class: "button", method: :delete, data: {confirm: "Are you sure?"} %>
  </section>
<% end %>