config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"

  get "events/filter/:show_only", to: "events#index", as: :filtered_events

  resources :categories
  
  # Since registrations only make sense in the context of events
  # we should nest the registrations routes under the event routes
  # This sets up a hierarchy: the event id must be present in the routes
  # for registrations path
  # like events/:id/registrations/new
  # the registration related routes are embeded under events/:id
  resources :events do
    resources :registrations
    resources :likes
  end

  # since there will be only one session per user, we use the singular form of resource and the resource name (:session)
  # this way the routes won't contain an :id param for destroying a session
  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "signup", to: "users#new"
    
  
  # get "events", to: "events#index"
  # get "events/new", to: "events#new"
  # get "events/:id", to: "events#show", as: "event"
  # get "events/:id/edit", to: "events#edit", as: "edit_event"
  # patch "events/:id", to: "events#update"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made in the <a href="http://pragmaticstudio.com">Pragmatic Studio</a>
    &copy; Copyright, <%= Time.now.strftime("%Y") %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag( "logo.png", title: "Events", alt: "Events logo"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "All Events", events_path %>
      </li>
      <li>
        <%= link_to "Upcoming", filtered_events_path(:upcoming) %>
      </li>
      <li>
        <%= link_to "Past", filtered_events_path(:past) %>
      </li>
      <li>
        <%= link_to "Free", filtered_events_path(:free) %>
      </li>
      <li>
        <%= link_to "Recent", filtered_events_path(:recent) %>
      </li>
      <%# <li> %>
        <%# adding query params to a link %>
        <%# <%= link_to "Upcoming Events", events_path(show_only: "upcoming") %>
      </li>
    </ul>

    <ul class="right">
      <%# current_user is a view helper %>
      <% if current_user %>
        <li>
          <%= link_to current_user.name, user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_session_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>